import Head from "next/head";
import EventList from "./events/EventList";

// export const metadata = {
//   title: "Next.js of HomePage",
//   description: "Generated by Next.js of HomePage",
// };

const HomePage = async () => {
  try {
    const res = await fetch(
      "https://react-get-start-16d8a-default-rtdb.asia-southeast1.firebasedatabase.app/events.json"
    );

    console.log(
      "Fetch completed, processing data at:",
      new Date().toISOString()
    );

    const data = await res.json(); // 等待 JSON 解析完成

    const items = data.filter((item) => item.isFeatured);

    return (
      <>
        <Head>
          <title>Next.js title by Head</title>
          <meta name="description" content="Next.js of Head's description" />
        </Head>
        <div className="flex flex-col items-center justify-center">
          <h2>HomePage</h2>
          <EventList items={items} />
        </div>
      </>
    );
  } catch (error) {
    console.error("Fetch failed:", error); // 捕获错误
    return <p>Error fetching data</p>;
  }
};

export default HomePage;
export const revalidate = 10;
