import localFont from "next/font/local";
import "./globals.css";
import {Inter} from "next/font/google";
import {cn} from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"
import BaseLayout from "@/components/layout/BaseLayout";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BaseLayout>
          {children}
          </BaseLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
