import BaseLayout from "@/components/BaseLayout";
import "./globals.css"; // global styles for all pages
import {ChakraProvider} from "@chakra-ui/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <BaseLayout>{children} </BaseLayout>
        </ChakraProvider>
      </body>
    </html>
  );
}
