# Generated by Django 4.2 on 2024-10-06 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlists', '0002_waitlistentry_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
